// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6y-logNaMw9aLOlZRKHpmW3jLFdkXrzw',
    appId: '1:147521517946:web:5a713d749e45a1eb1a7ec3',
    messagingSenderId: '147521517946',
    projectId: 'productsapp-1c963',
    authDomain: 'productsapp-1c963.firebaseapp.com',
    storageBucket: 'productsapp-1c963.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApqYaS4Q8TVQZWl1zmbXdnh0EgNms4Ru0',
    appId: '1:147521517946:android:7eac5b675d333c221a7ec3',
    messagingSenderId: '147521517946',
    projectId: 'productsapp-1c963',
    storageBucket: 'productsapp-1c963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7vK6oczRIWVk1q2zZAnSG-vA2kTuJl7g',
    appId: '1:147521517946:ios:681b547385ea6b331a7ec3',
    messagingSenderId: '147521517946',
    projectId: 'productsapp-1c963',
    storageBucket: 'productsapp-1c963.appspot.com',
    iosBundleId: 'com.example.recipeappFlutter',
  );
}
